import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import * as schema from "@shared/schema";

const { Pool } = pg;

export const hasDatabase = Boolean(process.env.DATABASE_URL);

export const pool = hasDatabase
  ? new Pool({
      connectionString: process.env.DATABASE_URL,
      ssl: process.env.NODE_ENV === "production" ? { rejectUnauthorized: false } : undefined,
    })
  : null;

export const db = pool ? drizzle(pool, { schema }) : null;

const appSchemaStatements = [
  `CREATE EXTENSION IF NOT EXISTS pgcrypto;`,
  `CREATE TABLE IF NOT EXISTS users (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    username text NOT NULL UNIQUE,
    password text NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS cms_pages (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    title text NOT NULL,
    slug text NOT NULL UNIQUE,
    status text NOT NULL DEFAULT 'draft',
    excerpt text,
    content jsonb NOT NULL DEFAULT '{"sections":[]}'::jsonb,
    seo jsonb NOT NULL DEFAULT '{}'::jsonb,
    published_at timestamp,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  );`,
  `CREATE TABLE IF NOT EXISTS cms_forms (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name text NOT NULL,
    slug text NOT NULL UNIQUE,
    description text,
    fields jsonb NOT NULL DEFAULT '[]'::jsonb,
    notification_email text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  );`,
  `CREATE TABLE IF NOT EXISTS cms_form_submissions (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    form_id varchar,
    form_slug text NOT NULL,
    name text,
    email text,
    phone text,
    service text,
    message text,
    fields jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'new',
    lead_id varchar,
    source_url text,
    referrer text,
    user_agent text,
    ip_address text,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  );`,
  `CREATE TABLE IF NOT EXISTS cms_blog_posts (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    title text NOT NULL,
    slug text NOT NULL UNIQUE,
    status text NOT NULL DEFAULT 'draft',
    excerpt text,
    body text NOT NULL DEFAULT '',
    featured_image_id varchar,
    tags jsonb NOT NULL DEFAULT '[]'::jsonb,
    category text,
    seo jsonb NOT NULL DEFAULT '{}'::jsonb,
    published_at timestamp,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  );`,
  `CREATE TABLE IF NOT EXISTS cms_media (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name text NOT NULL,
    url text NOT NULL,
    mime_type text NOT NULL,
    alt_text text,
    caption text,
    category text,
    tags jsonb NOT NULL DEFAULT '[]'::jsonb,
    is_gallery_ready boolean NOT NULL DEFAULT false,
    size_bytes integer,
    width integer,
    height integer,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  );`,
  `CREATE TABLE IF NOT EXISTS cms_sections (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name text NOT NULL,
    handle text NOT NULL UNIQUE,
    category text NOT NULL DEFAULT 'content',
    blocks jsonb NOT NULL DEFAULT '[]'::jsonb,
    is_reusable boolean NOT NULL DEFAULT true,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  );`,
  `CREATE TABLE IF NOT EXISTS cms_branding (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    site_name text NOT NULL DEFAULT 'Glass & Door Pro',
    tagline text,
    logo_url text,
    favicon_url text,
    phone text,
    email text,
    address text,
    social_links jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  );`,
  `CREATE TABLE IF NOT EXISTS cms_color_palettes (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name text NOT NULL,
    tokens jsonb NOT NULL,
    is_active boolean NOT NULL DEFAULT false,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  );`,
  `CREATE TABLE IF NOT EXISTS cms_typography (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name text NOT NULL,
    heading_font text NOT NULL DEFAULT 'Montserrat',
    body_font text NOT NULL DEFAULT 'Open Sans',
    scale jsonb NOT NULL DEFAULT '{}'::jsonb,
    is_active boolean NOT NULL DEFAULT false,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  );`,
  `CREATE TABLE IF NOT EXISTS cms_menus (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name text NOT NULL,
    location text NOT NULL,
    items jsonb NOT NULL DEFAULT '[]'::jsonb,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  );`,
  `CREATE TABLE IF NOT EXISTS cms_sidebars (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name text NOT NULL,
    location text NOT NULL,
    widgets jsonb NOT NULL DEFAULT '[]'::jsonb,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  );`,
  `CREATE TABLE IF NOT EXISTS cms_documentation (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    title text NOT NULL,
    slug text NOT NULL UNIQUE,
    body text NOT NULL DEFAULT '',
    category text NOT NULL DEFAULT 'Admin',
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  );`,
  `CREATE TABLE IF NOT EXISTS cms_system_backups (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name text NOT NULL,
    status text NOT NULL DEFAULT 'ready',
    manifest jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_by varchar,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  );`,
  `CREATE TABLE IF NOT EXISTS cms_system_users (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name text NOT NULL,
    email text NOT NULL UNIQUE,
    role text NOT NULL DEFAULT 'editor',
    status text NOT NULL DEFAULT 'active',
    last_login_at timestamp,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  );`,
  `CREATE TABLE IF NOT EXISTS cms_settings (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    key text NOT NULL UNIQUE,
    value jsonb NOT NULL DEFAULT '{}'::jsonb,
    "group" text NOT NULL DEFAULT 'general',
    is_public boolean NOT NULL DEFAULT false,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  );`,
  `CREATE TABLE IF NOT EXISTS crm_leads (
    id varchar PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name text NOT NULL,
    email text,
    phone text,
    service text,
    message text NOT NULL DEFAULT '',
    source text NOT NULL DEFAULT 'website',
    status text NOT NULL DEFAULT 'new',
    pipeline_stage text NOT NULL DEFAULT 'new',
    priority text NOT NULL DEFAULT 'normal',
    next_follow_up_at timestamp,
    notes text,
    assigned_to varchar,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  );`,
];

const appSchemaRepairStatements = [
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS username text;`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS password text;`,

  `ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS title text;`,
  `ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS slug text;`,
  `ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS status text DEFAULT 'draft';`,
  `ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS excerpt text;`,
  `ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS content jsonb DEFAULT '{"sections":[]}'::jsonb;`,
  `ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS seo jsonb DEFAULT '{}'::jsonb;`,
  `ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS published_at timestamp;`,
  `ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();`,
  `ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();`,
  `UPDATE cms_pages SET status = 'draft' WHERE status IS NULL;`,
  `UPDATE cms_pages SET content = '{"sections":[]}'::jsonb WHERE content IS NULL;`,
  `UPDATE cms_pages SET seo = '{}'::jsonb WHERE seo IS NULL;`,
  `UPDATE cms_pages SET created_at = now() WHERE created_at IS NULL;`,
  `UPDATE cms_pages SET updated_at = now() WHERE updated_at IS NULL;`,

  `ALTER TABLE cms_forms ADD COLUMN IF NOT EXISTS name text;`,
  `ALTER TABLE cms_forms ADD COLUMN IF NOT EXISTS slug text;`,
  `ALTER TABLE cms_forms ADD COLUMN IF NOT EXISTS description text;`,
  `ALTER TABLE cms_forms ADD COLUMN IF NOT EXISTS fields jsonb DEFAULT '[]'::jsonb;`,
  `ALTER TABLE cms_forms ADD COLUMN IF NOT EXISTS notification_email text;`,
  `ALTER TABLE cms_forms ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;`,
  `ALTER TABLE cms_forms ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();`,
  `ALTER TABLE cms_forms ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();`,
  `UPDATE cms_forms SET fields = '[]'::jsonb WHERE fields IS NULL;`,
  `UPDATE cms_forms SET is_active = true WHERE is_active IS NULL;`,
  `UPDATE cms_forms SET created_at = now() WHERE created_at IS NULL;`,
  `UPDATE cms_forms SET updated_at = now() WHERE updated_at IS NULL;`,

  `ALTER TABLE cms_form_submissions ADD COLUMN IF NOT EXISTS form_id varchar;`,
  `ALTER TABLE cms_form_submissions ADD COLUMN IF NOT EXISTS form_slug text;`,
  `ALTER TABLE cms_form_submissions ADD COLUMN IF NOT EXISTS name text;`,
  `ALTER TABLE cms_form_submissions ADD COLUMN IF NOT EXISTS email text;`,
  `ALTER TABLE cms_form_submissions ADD COLUMN IF NOT EXISTS phone text;`,
  `ALTER TABLE cms_form_submissions ADD COLUMN IF NOT EXISTS service text;`,
  `ALTER TABLE cms_form_submissions ADD COLUMN IF NOT EXISTS message text;`,
  `ALTER TABLE cms_form_submissions ADD COLUMN IF NOT EXISTS fields jsonb DEFAULT '{}'::jsonb;`,
  `ALTER TABLE cms_form_submissions ADD COLUMN IF NOT EXISTS status text DEFAULT 'new';`,
  `ALTER TABLE cms_form_submissions ADD COLUMN IF NOT EXISTS lead_id varchar;`,
  `ALTER TABLE cms_form_submissions ADD COLUMN IF NOT EXISTS source_url text;`,
  `ALTER TABLE cms_form_submissions ADD COLUMN IF NOT EXISTS referrer text;`,
  `ALTER TABLE cms_form_submissions ADD COLUMN IF NOT EXISTS user_agent text;`,
  `ALTER TABLE cms_form_submissions ADD COLUMN IF NOT EXISTS ip_address text;`,
  `ALTER TABLE cms_form_submissions ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();`,
  `ALTER TABLE cms_form_submissions ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();`,
  `UPDATE cms_form_submissions SET form_slug = 'website-quote-request' WHERE form_slug IS NULL;`,
  `UPDATE cms_form_submissions SET fields = '{}'::jsonb WHERE fields IS NULL;`,
  `UPDATE cms_form_submissions SET status = 'new' WHERE status IS NULL;`,
  `UPDATE cms_form_submissions SET created_at = now() WHERE created_at IS NULL;`,
  `UPDATE cms_form_submissions SET updated_at = now() WHERE updated_at IS NULL;`,

  `ALTER TABLE cms_blog_posts ADD COLUMN IF NOT EXISTS title text;`,
  `ALTER TABLE cms_blog_posts ADD COLUMN IF NOT EXISTS slug text;`,
  `ALTER TABLE cms_blog_posts ADD COLUMN IF NOT EXISTS status text DEFAULT 'draft';`,
  `ALTER TABLE cms_blog_posts ADD COLUMN IF NOT EXISTS excerpt text;`,
  `ALTER TABLE cms_blog_posts ADD COLUMN IF NOT EXISTS body text DEFAULT '';`,
  `ALTER TABLE cms_blog_posts ADD COLUMN IF NOT EXISTS featured_image_id varchar;`,
  `ALTER TABLE cms_blog_posts ADD COLUMN IF NOT EXISTS tags jsonb DEFAULT '[]'::jsonb;`,
  `ALTER TABLE cms_blog_posts ADD COLUMN IF NOT EXISTS category text;`,
  `ALTER TABLE cms_blog_posts ADD COLUMN IF NOT EXISTS seo jsonb DEFAULT '{}'::jsonb;`,
  `ALTER TABLE cms_blog_posts ADD COLUMN IF NOT EXISTS published_at timestamp;`,
  `ALTER TABLE cms_blog_posts ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();`,
  `ALTER TABLE cms_blog_posts ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();`,
  `UPDATE cms_blog_posts SET status = 'draft' WHERE status IS NULL;`,
  `UPDATE cms_blog_posts SET body = '' WHERE body IS NULL;`,
  `UPDATE cms_blog_posts SET tags = '[]'::jsonb WHERE tags IS NULL;`,
  `UPDATE cms_blog_posts SET seo = '{}'::jsonb WHERE seo IS NULL;`,
  `UPDATE cms_blog_posts SET created_at = now() WHERE created_at IS NULL;`,
  `UPDATE cms_blog_posts SET updated_at = now() WHERE updated_at IS NULL;`,

  `ALTER TABLE cms_media ADD COLUMN IF NOT EXISTS name text;`,
  `ALTER TABLE cms_media ADD COLUMN IF NOT EXISTS url text;`,
  `ALTER TABLE cms_media ADD COLUMN IF NOT EXISTS mime_type text;`,
  `ALTER TABLE cms_media ADD COLUMN IF NOT EXISTS alt_text text;`,
  `ALTER TABLE cms_media ADD COLUMN IF NOT EXISTS caption text;`,
  `ALTER TABLE cms_media ADD COLUMN IF NOT EXISTS category text;`,
  `ALTER TABLE cms_media ADD COLUMN IF NOT EXISTS tags jsonb DEFAULT '[]'::jsonb;`,
  `ALTER TABLE cms_media ADD COLUMN IF NOT EXISTS is_gallery_ready boolean DEFAULT false;`,
  `ALTER TABLE cms_media ADD COLUMN IF NOT EXISTS size_bytes integer;`,
  `ALTER TABLE cms_media ADD COLUMN IF NOT EXISTS width integer;`,
  `ALTER TABLE cms_media ADD COLUMN IF NOT EXISTS height integer;`,
  `ALTER TABLE cms_media ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();`,
  `ALTER TABLE cms_media ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();`,
  `UPDATE cms_media SET tags = '[]'::jsonb WHERE tags IS NULL;`,
  `UPDATE cms_media SET is_gallery_ready = false WHERE is_gallery_ready IS NULL;`,
  `UPDATE cms_media
    SET is_gallery_ready = true
    WHERE is_gallery_ready = false
      AND mime_type LIKE 'image/%'
      AND concat_ws(' ', url, name, caption, alt_text) ILIKE '%gallery%';`,
  `UPDATE cms_media SET created_at = now() WHERE created_at IS NULL;`,
  `UPDATE cms_media SET updated_at = now() WHERE updated_at IS NULL;`,

  `ALTER TABLE cms_sections ADD COLUMN IF NOT EXISTS name text;`,
  `ALTER TABLE cms_sections ADD COLUMN IF NOT EXISTS handle text;`,
  `ALTER TABLE cms_sections ADD COLUMN IF NOT EXISTS category text DEFAULT 'content';`,
  `ALTER TABLE cms_sections ADD COLUMN IF NOT EXISTS blocks jsonb DEFAULT '[]'::jsonb;`,
  `ALTER TABLE cms_sections ADD COLUMN IF NOT EXISTS is_reusable boolean DEFAULT true;`,
  `ALTER TABLE cms_sections ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();`,
  `ALTER TABLE cms_sections ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();`,
  `UPDATE cms_sections SET category = 'content' WHERE category IS NULL;`,
  `UPDATE cms_sections SET blocks = '[]'::jsonb WHERE blocks IS NULL;`,
  `UPDATE cms_sections SET is_reusable = true WHERE is_reusable IS NULL;`,
  `UPDATE cms_sections SET created_at = now() WHERE created_at IS NULL;`,
  `UPDATE cms_sections SET updated_at = now() WHERE updated_at IS NULL;`,

  `ALTER TABLE cms_branding ADD COLUMN IF NOT EXISTS site_name text DEFAULT 'Glass & Door Pro';`,
  `ALTER TABLE cms_branding ADD COLUMN IF NOT EXISTS tagline text;`,
  `ALTER TABLE cms_branding ADD COLUMN IF NOT EXISTS logo_url text;`,
  `ALTER TABLE cms_branding ADD COLUMN IF NOT EXISTS favicon_url text;`,
  `ALTER TABLE cms_branding ADD COLUMN IF NOT EXISTS phone text;`,
  `ALTER TABLE cms_branding ADD COLUMN IF NOT EXISTS email text;`,
  `ALTER TABLE cms_branding ADD COLUMN IF NOT EXISTS address text;`,
  `ALTER TABLE cms_branding ADD COLUMN IF NOT EXISTS social_links jsonb DEFAULT '{}'::jsonb;`,
  `ALTER TABLE cms_branding ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();`,
  `ALTER TABLE cms_branding ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();`,
  `UPDATE cms_branding SET site_name = 'Glass & Door Pro' WHERE site_name IS NULL;`,
  `UPDATE cms_branding SET social_links = '{}'::jsonb WHERE social_links IS NULL;`,
  `UPDATE cms_branding SET created_at = now() WHERE created_at IS NULL;`,
  `UPDATE cms_branding SET updated_at = now() WHERE updated_at IS NULL;`,

  `ALTER TABLE cms_color_palettes ADD COLUMN IF NOT EXISTS name text;`,
  `ALTER TABLE cms_color_palettes ADD COLUMN IF NOT EXISTS tokens jsonb DEFAULT '{}'::jsonb;`,
  `ALTER TABLE cms_color_palettes ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT false;`,
  `ALTER TABLE cms_color_palettes ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();`,
  `ALTER TABLE cms_color_palettes ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();`,
  `UPDATE cms_color_palettes SET tokens = '{}'::jsonb WHERE tokens IS NULL;`,
  `UPDATE cms_color_palettes SET is_active = false WHERE is_active IS NULL;`,
  `UPDATE cms_color_palettes SET created_at = now() WHERE created_at IS NULL;`,
  `UPDATE cms_color_palettes SET updated_at = now() WHERE updated_at IS NULL;`,

  `ALTER TABLE cms_typography ADD COLUMN IF NOT EXISTS name text;`,
  `ALTER TABLE cms_typography ADD COLUMN IF NOT EXISTS heading_font text DEFAULT 'Montserrat';`,
  `ALTER TABLE cms_typography ADD COLUMN IF NOT EXISTS body_font text DEFAULT 'Open Sans';`,
  `ALTER TABLE cms_typography ADD COLUMN IF NOT EXISTS scale jsonb DEFAULT '{}'::jsonb;`,
  `ALTER TABLE cms_typography ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT false;`,
  `ALTER TABLE cms_typography ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();`,
  `ALTER TABLE cms_typography ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();`,
  `UPDATE cms_typography SET heading_font = 'Montserrat' WHERE heading_font IS NULL;`,
  `UPDATE cms_typography SET body_font = 'Open Sans' WHERE body_font IS NULL;`,
  `UPDATE cms_typography SET scale = '{}'::jsonb WHERE scale IS NULL;`,
  `UPDATE cms_typography SET is_active = false WHERE is_active IS NULL;`,
  `UPDATE cms_typography SET created_at = now() WHERE created_at IS NULL;`,
  `UPDATE cms_typography SET updated_at = now() WHERE updated_at IS NULL;`,

  `ALTER TABLE cms_menus ADD COLUMN IF NOT EXISTS name text;`,
  `ALTER TABLE cms_menus ADD COLUMN IF NOT EXISTS location text;`,
  `ALTER TABLE cms_menus ADD COLUMN IF NOT EXISTS items jsonb DEFAULT '[]'::jsonb;`,
  `ALTER TABLE cms_menus ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;`,
  `ALTER TABLE cms_menus ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();`,
  `ALTER TABLE cms_menus ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();`,
  `UPDATE cms_menus SET items = '[]'::jsonb WHERE items IS NULL;`,
  `UPDATE cms_menus SET is_active = true WHERE is_active IS NULL;`,
  `UPDATE cms_menus SET created_at = now() WHERE created_at IS NULL;`,
  `UPDATE cms_menus SET updated_at = now() WHERE updated_at IS NULL;`,

  `ALTER TABLE cms_sidebars ADD COLUMN IF NOT EXISTS name text;`,
  `ALTER TABLE cms_sidebars ADD COLUMN IF NOT EXISTS location text;`,
  `ALTER TABLE cms_sidebars ADD COLUMN IF NOT EXISTS widgets jsonb DEFAULT '[]'::jsonb;`,
  `ALTER TABLE cms_sidebars ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;`,
  `ALTER TABLE cms_sidebars ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();`,
  `ALTER TABLE cms_sidebars ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();`,
  `UPDATE cms_sidebars SET widgets = '[]'::jsonb WHERE widgets IS NULL;`,
  `UPDATE cms_sidebars SET is_active = true WHERE is_active IS NULL;`,
  `UPDATE cms_sidebars SET created_at = now() WHERE created_at IS NULL;`,
  `UPDATE cms_sidebars SET updated_at = now() WHERE updated_at IS NULL;`,

  `ALTER TABLE cms_documentation ADD COLUMN IF NOT EXISTS title text;`,
  `ALTER TABLE cms_documentation ADD COLUMN IF NOT EXISTS slug text;`,
  `ALTER TABLE cms_documentation ADD COLUMN IF NOT EXISTS body text DEFAULT '';`,
  `ALTER TABLE cms_documentation ADD COLUMN IF NOT EXISTS category text DEFAULT 'Admin';`,
  `ALTER TABLE cms_documentation ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();`,
  `ALTER TABLE cms_documentation ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();`,
  `UPDATE cms_documentation SET body = '' WHERE body IS NULL;`,
  `UPDATE cms_documentation SET category = 'Admin' WHERE category IS NULL;`,
  `UPDATE cms_documentation SET created_at = now() WHERE created_at IS NULL;`,
  `UPDATE cms_documentation SET updated_at = now() WHERE updated_at IS NULL;`,

  `ALTER TABLE cms_system_backups ADD COLUMN IF NOT EXISTS name text;`,
  `ALTER TABLE cms_system_backups ADD COLUMN IF NOT EXISTS status text DEFAULT 'ready';`,
  `ALTER TABLE cms_system_backups ADD COLUMN IF NOT EXISTS manifest jsonb DEFAULT '{}'::jsonb;`,
  `ALTER TABLE cms_system_backups ADD COLUMN IF NOT EXISTS created_by varchar;`,
  `ALTER TABLE cms_system_backups ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();`,
  `ALTER TABLE cms_system_backups ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();`,
  `UPDATE cms_system_backups SET status = 'ready' WHERE status IS NULL;`,
  `UPDATE cms_system_backups SET manifest = '{}'::jsonb WHERE manifest IS NULL;`,
  `UPDATE cms_system_backups SET created_at = now() WHERE created_at IS NULL;`,
  `UPDATE cms_system_backups SET updated_at = now() WHERE updated_at IS NULL;`,

  `ALTER TABLE cms_system_users ADD COLUMN IF NOT EXISTS name text;`,
  `ALTER TABLE cms_system_users ADD COLUMN IF NOT EXISTS email text;`,
  `ALTER TABLE cms_system_users ADD COLUMN IF NOT EXISTS role text DEFAULT 'editor';`,
  `ALTER TABLE cms_system_users ADD COLUMN IF NOT EXISTS status text DEFAULT 'active';`,
  `ALTER TABLE cms_system_users ADD COLUMN IF NOT EXISTS last_login_at timestamp;`,
  `ALTER TABLE cms_system_users ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();`,
  `ALTER TABLE cms_system_users ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();`,
  `UPDATE cms_system_users SET role = 'editor' WHERE role IS NULL;`,
  `UPDATE cms_system_users SET status = 'active' WHERE status IS NULL;`,
  `UPDATE cms_system_users SET created_at = now() WHERE created_at IS NULL;`,
  `UPDATE cms_system_users SET updated_at = now() WHERE updated_at IS NULL;`,

  `ALTER TABLE cms_settings ADD COLUMN IF NOT EXISTS key text;`,
  `ALTER TABLE cms_settings ADD COLUMN IF NOT EXISTS value jsonb DEFAULT '{}'::jsonb;`,
  `ALTER TABLE cms_settings ADD COLUMN IF NOT EXISTS "group" text DEFAULT 'general';`,
  `ALTER TABLE cms_settings ADD COLUMN IF NOT EXISTS is_public boolean DEFAULT false;`,
  `ALTER TABLE cms_settings ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();`,
  `ALTER TABLE cms_settings ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();`,
  `UPDATE cms_settings SET value = '{}'::jsonb WHERE value IS NULL;`,
  `UPDATE cms_settings SET "group" = 'general' WHERE "group" IS NULL;`,
  `UPDATE cms_settings SET is_public = false WHERE is_public IS NULL;`,
  `UPDATE cms_settings SET created_at = now() WHERE created_at IS NULL;`,
  `UPDATE cms_settings SET updated_at = now() WHERE updated_at IS NULL;`,

  `ALTER TABLE crm_leads ADD COLUMN IF NOT EXISTS name text;`,
  `ALTER TABLE crm_leads ADD COLUMN IF NOT EXISTS email text;`,
  `ALTER TABLE crm_leads ADD COLUMN IF NOT EXISTS phone text;`,
  `ALTER TABLE crm_leads ADD COLUMN IF NOT EXISTS service text;`,
  `ALTER TABLE crm_leads ADD COLUMN IF NOT EXISTS message text DEFAULT '';`,
  `ALTER TABLE crm_leads ADD COLUMN IF NOT EXISTS source text DEFAULT 'website';`,
  `ALTER TABLE crm_leads ADD COLUMN IF NOT EXISTS status text DEFAULT 'new';`,
  `ALTER TABLE crm_leads ADD COLUMN IF NOT EXISTS pipeline_stage text DEFAULT 'new';`,
  `ALTER TABLE crm_leads ADD COLUMN IF NOT EXISTS priority text DEFAULT 'normal';`,
  `ALTER TABLE crm_leads ADD COLUMN IF NOT EXISTS next_follow_up_at timestamp;`,
  `ALTER TABLE crm_leads ADD COLUMN IF NOT EXISTS notes text;`,
  `ALTER TABLE crm_leads ADD COLUMN IF NOT EXISTS assigned_to varchar;`,
  `ALTER TABLE crm_leads ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();`,
  `ALTER TABLE crm_leads ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();`,
  `UPDATE crm_leads SET message = '' WHERE message IS NULL;`,
  `UPDATE crm_leads SET source = 'website' WHERE source IS NULL;`,
  `UPDATE crm_leads SET status = 'new' WHERE status IS NULL;`,
  `UPDATE crm_leads SET pipeline_stage = 'new' WHERE pipeline_stage IS NULL;`,
  `UPDATE crm_leads SET priority = 'normal' WHERE priority IS NULL;`,
  `UPDATE crm_leads SET created_at = now() WHERE created_at IS NULL;`,
  `UPDATE crm_leads SET updated_at = now() WHERE updated_at IS NULL;`,
];

export async function ensureDatabaseSchema() {
  if (!pool) return;

  for (const statement of appSchemaStatements) {
    await pool.query(statement);
  }

  for (const statement of appSchemaRepairStatements) {
    await pool.query(statement);
  }
}

export function getDatabaseProvisioningStatus() {
  return {
    createsMissingTables: true,
    repairsMissingColumns: true,
    createStatements: appSchemaStatements.length,
    repairStatements: appSchemaRepairStatements.length,
  };
}
